name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }}-hosted
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        include:
          - os: windows-2019
            triplet: x86-windows
          - os: ubuntu-18.04
            triplet: x64-linux
          - os: macos-10.15
            triplet: x64-osx

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: 'CMake+Makefiles'
      uses: lukka/run-cmake@v2
      if: contains( matrix.os, 'ubuntu')
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '${{ runner.workspace }}/b/unixmakefiles'
        cmakeAppendedArgs: '-G"Unix Makefiles"'
        
    - name: 'CMake+Visual Studio 15 2017'
      uses: lukka/run-cmake@v2
      if: contains( matrix.os, 'windows')
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '${{ runner.workspace }}/b/vs2017'
        cmakeAppendedArgs: '-G"Visual Studio 15 2017"'
  
    - name: 'CMake+XCode'
      uses: lukka/run-cmake@v2
      if: contains( matrix.os, 'macos')
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '${{ runner.workspace }}/b/xcode'
        cmakeAppendedArgs: '-GXcode'
